# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRpeRubbVfRHMuCvW-DiNVHH5CnRER_E
"""

"""
Script principal de execução do pipeline.
"""

from sklearn.metrics import classification_report, f1_score
from src.system import TuberculosisDecisionSystem
from src.utils import plot_global_xai


def main():
    data_path = "data/tuberculosis.csv"
    target_column = "sitAtual"

    print("Iniciando o Sistema Multiagente para Tuberculose...")
    system = TuberculosisDecisionSystem(data_path=data_path, target=target_column)

    results = system.run()
    best_threshold = results["best_threshold"]
    y_test = results["y_test"]
    y_prob = results["y_prob"]

    y_pred = (y_prob >= best_threshold).astype(int)

    print("\n--- Resultados de Desempenho ---")
    print(f"Limiar Otimizado: {best_threshold:.2f}")
    print(f"F1 Score macro: {f1_score(y_test, y_pred, average='macro'):.4f}")
    print("\nRelatório do Modelo:\n")
    print(classification_report(y_test, y_pred))

    print("\nGerando Gráficos de Explicabilidade (XAI)...")
    plot_global_xai(results["global_xai"])
    print("Concluído! Imagem gerada em: global_xai.png")


if __name__ == "__main__":
    main()