# -*- coding: utf-8 -*-
"""agents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRpeRubbVfRHMuCvW-DiNVHH5CnRER_E
"""

"""
Módulo de Agentes Inteligentes para Predição e Decisão Clínico-Epidemiológica.

Contém as definições dos agentes responsáveis pelo pré-processamento de dados,
treinamento do modelo preditivo, otimização de limiares, explicabilidade (XAI)
e suporte à tomada de decisão clínica.
"""

from typing import Dict, List, Tuple, Any, Optional
import numpy as np
import pandas as pd
import shap
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier


class Message:
    """Representa uma mensagem trocada entre agentes dentro do sistema."""

    def __init__(
        self,
        sender: str,
        receiver: str,
        content: Dict[str, Any],
        performative: str = "inform"
    ) -> None:
        """
        Inicializa a estrutura da mensagem.

        Args:
            sender: Nome do agente remetente.
            receiver: Nome do agente destinatário.
            content: Conteúdo útil ou payload da mensagem.
            performative: Intenção comunicativa (ex: 'inform', 'request').
        """
        self.sender = sender
        self.receiver = receiver
        self.content = content
        self.performative = performative


class BaseAgent:
    """Classe base genérica para a criação de agentes na arquitetura."""

    def __init__(self, name: str) -> None:
        """
        Inicializa o agente base com seu nome.

        Args:
            name: Identificador único do agente.
        """
        self.name = name

    def send(self, message: Message, receiver: "BaseAgent") -> None:
        """Envia uma mensagem para outro agente."""
        receiver.receive(message)

    def receive(self, message: Message) -> None:
        """Método abstrato para o recebimento de mensagens."""
        pass


class DataAgent(BaseAgent):
    """
    Agente responsável pelas etapas de carga, limpeza, codificação,
    divisão estratificada dos dados e seleção de atributos relevantes.
    """

    def __init__(self, path: str, target: str) -> None:
        """
        Inicializa o DataAgent.

        Args:
            path: Caminho do arquivo CSV de dados.
            target: Nome da coluna que representa a variável alvo.
        """
        super().__init__("DataAgent")
        self.path = path
        self.target = target
        self.encoders: Dict[str, LabelEncoder] = {}
        self.selected_features: Optional[List[str]] = None

    def load_data(self) -> pd.DataFrame:
        """
        Carrega a base de dados em formato CSV e remove colunas de índice legado.

        Returns:
            pd.DataFrame: DataFrame contendo os dados brutos.
        """
        df = pd.read_csv(self.path)
        return df.drop(columns=["Unnamed: 0"], errors="ignore")

    def preprocess(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Aplica Label Encoding nas variáveis categóricas e imputação pela mediana.

        Args:
            df: DataFrame com dados brutos.

        Returns:
            pd.DataFrame: DataFrame tratado e numérico.
        """
        df_clean = df.copy()

        # Encodar variáveis do tipo objeto/categóricas
        for col in df_clean.select_dtypes(include="object").columns:
            le = LabelEncoder()
            df_clean[col] = le.fit_transform(df_clean[col].astype(str))
            self.encoders[col] = le

        # Imputação de valores ausentes utilizando a mediana
        return df_clean.fillna(df_clean.median(numeric_only=True))

    def select_features(
        self,
        X: pd.DataFrame,
        y: pd.Series,
        top_k: int = 10
    ) -> pd.DataFrame:
        """
        Aplica seleção de atributos (Embedded Feature Selection) baseada no
        ganho de informação obtido por uma árvore XGBoost preliminar.

        Args:
            X: Atributos preditivos de treino.
            y: Variável alvo de treino.
            top_k: Quantidade de atributos com maior relevância a selecionar.

        Returns:
            pd.DataFrame: Conjunto reduzido com as top_k colunas.
        """
        selector_model = XGBClassifier(random_state=42, eval_metric="logloss")
        selector_model.fit(X, y)

        importances = selector_model.feature_importances_
        indices = np.argsort(importances)[-top_k:]
        self.selected_features = X.columns[indices].tolist()

        return X[self.selected_features]

    def split(
        self,
        df: pd.DataFrame,
        test_size: float = 0.3,
        random_state: int = 42
    ) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
        """
        Realiza a divisão entre dados de treino e teste mantendo a proporção de classes.

        Args:
            df: DataFrame completo e limpo.
            test_size: Proporção do conjunto reservada para testes.
            random_state: Semente de aleatoriedade para reprodutibilidade.

        Returns:
            Tuple contendo (X_train, X_test, y_train, y_test).
        """
        X = df.drop(columns=[self.target])
        y = df[self.target]

        return train_test_split(
            X,
            y,
            test_size=test_size,
            random_state=random_state,
            stratify=y
        )


class PredictiveAgent(BaseAgent):
    """Agente responsável pelo treinamento e geração de inferências probabilísticas."""

    def __init__(self) -> None:
        """Inicializa o modelo preditivo XGBoost com hiperparâmetros ajustados."""
        super().__init__("PredictiveAgent")
        self.model = XGBClassifier(
            n_estimators=200,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="logloss",
            random_state=42,
        )

    def train(self, X: pd.DataFrame, y: pd.Series) -> None:
        """Ajusta o modelo XGBoost aos dados de treino."""
        self.model.fit(X, y)

    def predict_proba(self, X: pd.DataFrame) -> np.ndarray:
        """
        Retorna as probabilidades preditas para a classe positiva (desfecho de interesse).

        Args:
            X: Atributos preditivos.

        Returns:
            np.ndarray: Probabilidades estimadas para a classe 1.
        """
        return self.model.predict_proba(X)[:, 1]


class EvaluationAgent(BaseAgent):
    """Agente encarregado da avaliação de desempenho e otimização do limiar de decisão."""

    def __init__(self) -> None:
        """Inicializa o agente de avaliação."""
        super().__init__("EvaluationAgent")

    def find_best_threshold(
        self,
        y_true: pd.Series,
        y_prob: np.ndarray
    ) -> Tuple[float, float]:
        """
        Varre limiares entre 0.05 e 0.95 para encontrar o valor que maximiza
        o F1 Score macro.

        Args:
            y_true: Rótulos reais dos dados de teste.
            y_prob: Probabilidades preditas pelo modelo.

        Returns:
            Tuple contendo (melhor_threshold, melhor_f1_score_macro).
        """
        thresholds = np.linspace(0.05, 0.95, 91)
        best_t, best_f1 = 0.5, 0.0

        for t in thresholds:
            y_pred = (y_prob >= t).astype(int)
            f1 = f1_score(y_true, y_pred, average="macro")

            if f1 > best_f1:
                best_f1 = f1
                best_t = t

        return float(best_t), float(best_f1)


class ExplainabilityAgent(BaseAgent):
    """Agente de Inteligência Artificial Explicável (XAI) baseado nos valores SHAP."""

    def __init__(self, model: Any) -> None:
        """
        Inicializa o explicitador baseado em árvores.

        Args:
            model: Modelo preditivo já treinado.
        """
        super().__init__("ExplainabilityAgent")
        self.explainer = shap.TreeExplainer(model)

    def global_importance(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Calcula a importância média absoluta dos valores SHAP para cada atributo.

        Args:
            X: Base de dados de teste ou amostra.

        Returns:
            pd.DataFrame: Ranking das variáveis por impacto na decisão.
        """
        shap_values = self.explainer.shap_values(X)
        shap_used = shap_values[1] if isinstance(shap_values, list) else shap_values
        importance = np.abs(shap_used).mean(axis=0)

        return pd.DataFrame({
            "Feature": X.columns,
            "Importance": importance
        }).sort_values(by="Importance", ascending=False)

    def local_explanation(self, X_instance: pd.DataFrame) -> pd.Series:
        """
        Calcula as contribuições SHAP individuais para uma única instância.

        Args:
            X_instance: DataFrame contendo exatamente 1 linha (amostra do paciente).

        Returns:
            pd.Series: Atributos e suas respectivas contribuições numéricas.
        """
        shap_values = self.explainer.shap_values(X_instance)
        shap_used = shap_values[1] if isinstance(shap_values, list) else shap_values

        return pd.Series(
            shap_used[0],
            index=X_instance.columns
        ).sort_values(key=abs, ascending=False)


class DecisionSupportAgent(BaseAgent):
    """Agente de consolidação das saídas para relatórios explicativos ao profissional."""

    def __init__(self) -> None:
        """Inicializa o agente de apoio à decisão."""
        super().__init__("DecisionSupportAgent")

    def decide(
        self,
        prob: float,
        threshold: float,
        explanation: pd.Series,
        top_k: int = 5
    ) -> Dict[str, Any]:
        """
        Converte as probabilidades e contribuições SHAP em uma decisão clínica formatada.

        Args:
            prob: Probabilidade calculada do desfecho.
            threshold: Limiar ótimo de decisão obtido.
            explanation: Série temporal ou lista com valores SHAP individuais.
            top_k: Número de fatores determinantes a incluir na resposta.

        Returns:
            Dict com o desfecho estimado e os principais fatores preditivos.
        """
        decision = (
            "DESFECHO DESFAVORÁVEL"
            if prob >= threshold
            else "DESFECHO FAVORÁVEL"
        )

        return {
            "decisao": decision,
            "probabilidade": float(prob),
            "threshold": float(threshold),
            "principais_fatores": explanation.head(top_k).to_dict()
        }