# -*- coding: utf-8 -*-
"""system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRpeRubbVfRHMuCvW-DiNVHH5CnRER_E
"""

"""
Módulo de Orquestração do Sistema Multiagente para Tuberculose.

Este arquivo orquestra o fluxo de dados entre os diferentes agentes,
garantindo o balanceamento adequado no conjunto de treino, seleção de variáveis,
avaliação de métricas e explicabilidade dos resultados.
"""

from typing import Dict, Any
import pandas as pd
from imblearn.combine import SMOTETomek

from src.agents import (
    DataAgent,
    PredictiveAgent,
    EvaluationAgent,
    ExplainabilityAgent,
    DecisionSupportAgent
)


class TuberculosisDecisionSystem:
    """
    Orquestrador responsável pelo ciclo de vida completo da pipeline multiagente.
    """

    def __init__(self, data_path: str, target: str) -> None:
        """
        Inicializa o sistema orquestrador e instancia todos os agentes do pipeline.

        Args:
            data_path: Caminho completo ou relativo para o arquivo contendo os dados.
            target: Nome da variável que contém a classe de desfecho.
        """
        self.data_agent = DataAgent(data_path, target)
        self.model_agent = PredictiveAgent()
        self.eval_agent = EvaluationAgent()
        self.decision_agent = DecisionSupportAgent()

    def run() -> Dict[str, Any]:
        """
        Executa a pipeline completa:
        1. Carga e tratamento dos dados (DataAgent)
        2. Divisão estratificada e seleção das top-10 variáveis (DataAgent)
        3. Balanceamento via SMOTETomek no conjunto de treino
        4. Treinamento do classificador XGBoost (PredictiveAgent)
        5. Busca do threshold ótimo para F1-Macro (EvaluationAgent)
        6. Análise global e local de explicabilidade via SHAP (ExplainabilityAgent)
        7. Construção do relatório de recomendação (DecisionSupportAgent)

        Returns:
            Dict contendo os dados do relatório, modelo, dados de teste e explicações SHAP.
        """
        # 1. Carregamento dos dados brutos
        df = self.data_agent.load_data()

        # 2. Pré-processamento (Label Encoding e Imputação)
        df = self.data_agent.preprocess(df)

        # 3. Divisão Estratificada (Treino / Teste)
        X_train, X_test, y_train, y_test = self.data_agent.split(df)

        # 4. Seleção de Atributos via Feature Importance (Top 10)
        X_train_selected = self.data_agent.select_features(X_train, y_train, top_k=10)
        X_test_selected = X_test[self.data_agent.selected_features]

        # 5. Balanceamento dos dados (Aplica SMOTETomek exclusivamente no treino)
        sm = SMOTETomek(random_state=42)
        X_train_bal, y_train_bal = sm.fit_resample(X_train_selected, y_train)

        # 6. Aprendizado do Modelo
        self.model_agent.train(X_train_bal, y_train_bal)

        # 7. Inferência Probabilística
        y_prob = self.model_agent.predict_proba(X_test_selected)

        # 8. Otimização de Limiar de Decisão
        best_t, best_f1 = self.eval_agent.find_best_threshold(y_test, y_prob)

        # 9. Geração de Explicações SHAP
        expl_agent = ExplainabilityAgent(self.model_agent.model)
        global_xai = expl_agent.global_importance(X_test_selected)
        local_xai = expl_agent.local_explanation(X_test_selected.iloc[[0]])

        # 10. Construção do Relatório do Apoio à Decisão (Primeira instância de teste)
        decision = self.decision_agent.decide(
            prob=y_prob[0],
            threshold=best_t,
            explanation=local_xai
        )

        return {
            "decision": decision,
            "X_test": X_test_selected,
            "y_test": y_test,
            "y_prob": y_prob,
            "best_threshold": best_t,
            "global_xai": global_xai,
            "model": self.model_agent.model,
            "selected_features": self.data_agent.selected_features
        }
