# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRpeRubbVfRHMuCvW-DiNVHH5CnRER_E
"""

"""
Utilitários para geração de gráficos e avaliações comparativas do modelo.
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    auc,
    confusion_matrix,
    precision_recall_curve,
    roc_curve,
    average_precision_score,
)


def plot_global_xai(global_xai: pd.DataFrame, output_path: str = "global_xai.png") -> None:
    """Gera e salva o gráfico com o ranking global de importância SHAP."""
    top_features = global_xai.head(10)
    colors = sns.color_palette("Set2", len(top_features))

    plt.figure(figsize=(7, 5))
    plt.barh(top_features["Feature"], top_features["Importance"], color=colors)
    plt.gca().invert_yaxis()
    plt.xlabel("Impacto médio na decisão (SHAP)")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()


def plot_comparative_roc_pr(
    y_test, y_prob_nb, y_prob_sm, output_path: str = "Curva_ROC_PR_Comparacao.png"
) -> None:
    """Plota lado a lado a comparação de curvas ROC e Precision-Recall."""
    fpr_nb, tpr_nb, _ = roc_curve(y_test, y_prob_nb)
    auc_nb = auc(fpr_nb, tpr_nb)

    fpr_sm, tpr_sm, _ = roc_curve(y_test, y_prob_sm)
    auc_sm = auc(fpr_sm, tpr_sm)

    precision_nb, recall_nb, _ = precision_recall_curve(y_test, y_prob_nb)
    ap_nb = average_precision_score(y_test, y_prob_nb)

    precision_sm, recall_sm, _ = precision_recall_curve(y_test, y_prob_sm)
    ap_sm = average_precision_score(y_test, y_prob_sm)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # ROC Curve
    axes[0].plot(fpr_nb, tpr_nb, label=f"Sem balanceamento (AUC={auc_nb:.3f})")
    axes[0].plot(fpr_sm, tpr_sm, label=f"Com SMOTETomek (AUC={auc_sm:.3f})")
    axes[0].plot([0, 1], [0, 1], linestyle="--", color="gray")
    axes[0].set_xlabel("False Positive Rate")
    axes[0].set_ylabel("True Positive Rate")
    axes[0].set_title("Comparação ROC")
    axes[0].legend()
    axes[0].grid(True)

    # Precision-Recall Curve
    axes[1].plot(recall_nb, precision_nb, label=f"Sem balanceamento (AP={ap_nb:.3f})")
    axes[1].plot(recall_sm, precision_sm, label=f"Com SMOTETomek (AP={ap_sm:.3f})")
    axes[1].set_xlabel("Recall")
    axes[1].set_ylabel("Precision")
    axes[1].set_title("Comparação Precision–Recall")
    axes[1].legend()
    axes[1].grid(True)

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()